#!/bin/bash
if [ -n "$NAUTILUS_SCRIPT_SELECTED_URIS" ]; then
	gksu  gnome-open $NAUTILUS_SCRIPT_SELECTED_URIS &	
else
	#destination="`echo "$NAUTILUS_SCRIPT_CURRENT_URI" | sed 's/^file:\/\///'`"	
	gksu gnome-open $NAUTILUS_SCRIPT_CURRENT_URI & 
fi
exit 0

#for uri in $NAUTILUS_SCRIPT_SELECTED_URIS; do 
#	sudo gnome-open $uri & 
#done
#exit 0
